apiVersion: v1
kind: ConfigMap
metadata:
  name: ngrok
data:
  ngrok.cfg: |
    server_addr: "stockmonitor.info:4443"
    trust_host_root_certs: false
    tunnels:
      dashboard:
       subdomain: "dashboard"
       proto:
        http: grafana:3000
      api:
       subdomain: "api"
       proto:
        http: stock-api:80
